### ISSUE TITLE
Undefined index: templates

### ISSUE THREAD

**Issue by reblutus** [OutlawPlz/ckeditor_templates#1]
I get this error when I get to the admin/config/content/formats/manage/basic_html page

Notice: Undefined index: templates in Drupal\ckeditor_templates\Plugin\CKEditorPlugin\Templates->getConfig() (line 137 of modules/custom/ckeditor_templates/src/Plugin/CKEditorPlugin/Templates.php).

How do I fix this plz?

I'm on Drupal 8.1.2-dev

**Comment by OutlawPlz** [comment]
Hi Reblutus,

Could you provide me your template definition and the name you've insert into name setting?

**Comment by reblutus** [comment]
Hi, I took your module as is and followed your instruction on how to install it. I found another one that worked perfectly: [https://github.com/mattiasaxelsson/ckeditor_templates](url)

**Comment by OutlawPlz** [comment]
If there's a bug I would like to fix it. Anyway I'm glad you've found another solution. 

**Cannot reproduce.**
